/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PageTwoRouteImport } from './routes/page-two'
import { Route as PageThreeRouteImport } from './routes/page-three'
import { Route as FinalRouteImport } from './routes/final'
import { Route as IndexRouteImport } from './routes/index'

const PageTwoRoute = PageTwoRouteImport.update({
  id: '/page-two',
  path: '/page-two',
  getParentRoute: () => rootRouteImport,
} as any)
const PageThreeRoute = PageThreeRouteImport.update({
  id: '/page-three',
  path: '/page-three',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalRoute = FinalRouteImport.update({
  id: '/final',
  path: '/final',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/final': typeof FinalRoute
  '/page-three': typeof PageThreeRoute
  '/page-two': typeof PageTwoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/final': typeof FinalRoute
  '/page-three': typeof PageThreeRoute
  '/page-two': typeof PageTwoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/final': typeof FinalRoute
  '/page-three': typeof PageThreeRoute
  '/page-two': typeof PageTwoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/final' | '/page-three' | '/page-two'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/final' | '/page-three' | '/page-two'
  id: '__root__' | '/' | '/final' | '/page-three' | '/page-two'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinalRoute: typeof FinalRoute
  PageThreeRoute: typeof PageThreeRoute
  PageTwoRoute: typeof PageTwoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/page-two': {
      id: '/page-two'
      path: '/page-two'
      fullPath: '/page-two'
      preLoaderRoute: typeof PageTwoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page-three': {
      id: '/page-three'
      path: '/page-three'
      fullPath: '/page-three'
      preLoaderRoute: typeof PageThreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final': {
      id: '/final'
      path: '/final'
      fullPath: '/final'
      preLoaderRoute: typeof FinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinalRoute: FinalRoute,
  PageThreeRoute: PageThreeRoute,
  PageTwoRoute: PageTwoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
